import time
from datetime import date

from search import search_category
from llm import summarize_with_llm, write_executive_summary


def build_briefing(company: str) -> str:
    categories = {
        "Product Launches": f"{company} new product launch announcement 2026",
        "Funding & Financials": f"{company} funding round valuation 2026",
        "Partnerships & Notable Moves": f"{company} partnership announcement 2026",
        "Leadership & Public Statements": f"{company} executive statement leadership 2026",
    }

    briefing_sections = []
    for category_name, query in categories.items():
        print(f"Searching: {category_name}...")
        raw_results = search_category(company, query)
        summary = summarize_with_llm(company, category_name, raw_results)
        briefing_sections.append(f"## {category_name}\n{summary}\n")
        time.sleep(13)

    return "\n".join(briefing_sections)


def format_full_briefing(company: str, briefing_body: str, exec_summary: str) -> str:
    today = date.today().isoformat()
    return f"""# Competitive Intelligence Briefing: {company}
### Generated: {today}

## Executive Summary
{exec_summary}

---

{briefing_body}

---
*This briefing was generated by an AI agent. Verify facts against sources
before using in a business decision.*
"""


def save_briefing(company: str, full_briefing: str) -> str:
    today = date.today().isoformat()
    output_path = f"briefing_{company.lower()}_{today}.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_briefing)
    return output_path